#!/usr/bin/env python
from config import Configuration
config = Configuration.from_directory("/home/leonardr/programming/botbuddy/bots")
for model in config.bots:
    post = model.implementation.run()
