#!/usr/bin/env python
from config import Configuration
import sys
config = Configuration.from_directory(sys.argv[1])
for model in config.bots:
    post = model.implementation.new_post()
    print post.content
    for publication in post.publish():
        print publication.display()
    model.schedule_next_post(self, post)
config._db.commit()
